# Generated by Django 4.2.5 on 2023-09-21 23:10

import dei0.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('gluten', 'Gluten'), ('fat', 'Fat'), ('sodium', 'Sodium'), ('sugar', 'Sugar'), ('other', 'Other')], default='other', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('types', models.ManyToManyField(default=dei0.models.AlimentType.get_default_other_type, to='dei0.alimenttype')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measure_unit', models.CharField(choices=[('kg', 'Kilogram'), ('lt', 'Liter'), ('gr', 'Gram'), ('unit', 'Unit')], max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dei0.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparation', models.TextField()),
                ('ingredients', models.ManyToManyField(to='dei0.ingredientinrecipe')),
            ],
        ),
    ]
